# Example data sources 
rss_feeds:
  - "https://www.cnbc.com/id/100003114/device/rss/rss.html"
  - "https://www.reuters.com/markets/us/rss"

price_source: "yfinance"

database:
  # real setup can be .env DATABASE_URL
  url: "sqlite:///finnews_demo.sqlite"